apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import SignUpView, ChangePasswordView, SignInView


urlpatterns = [
    path("sign-in/", SignInView.as_view(), name="sign-in"),
    path("sign-up/", SignUpView.as_view(), name="sign-up"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        ChangePasswordView.as_view(),
        name="password_change",
    ),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.users.urls')),
    path('clients/', include('apps.clients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
# Comment out all this code if you don't want to use custom.
# The custom uses email for login instead of user.

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManagerCustom(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("E-mail é obrigatório.")
        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        # extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser precisa ser 'is_superuser=True'.")
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser precisa ser 'is_staff=True'.")
        return self._create_user(email, password, **extra_fields)


class UserCustom(AbstractUser):
    email = models.EmailField("E-mail", unique=True)
    first_name = models.CharField(
        "Primeiro nome", max_length=100, error_messages={"required": "Not null"}
    )
    last_name = models.CharField(
        "Ultimo nome", max_length=100, error_messages={"required": "Not null"}
    )
    # cell_phone = models.CharField('Celular', max_length=18)
    is_staff = models.BooleanField("Membro", default=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return self.email

    objects = UserManagerCustom()

apps/users/forms.py
from django import forms
from django.contrib.auth.models import Permission

# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from contextlib import suppress

# from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from .models import UserCustom
from crispy_forms.helper import FormHelper
from .layouts import layout_user_create, layout_auth


class AuthenticationFormCustom(AuthenticationForm):
    # __init__ Django Crispy
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.form_show_labels = True
        self.fields["username"].widget = forms.TextInput(attrs={"type": "email"})
        self.helper.layout = layout_auth

    class Meta:
        fields = ["username", "password"]
        labels = {"username": "E-Maill"}


class UserCreationFormCustom(UserCreationForm):
    PERM_VIEWS = [
        "Can view Client",
    ]

    class Meta:
        model = UserCustom
        fields = ["username", "first_name", "last_name"]
        labels = {"username": "E-Mail"}
        widgets = {
            "username": forms.TextInput(attrs={"type": "email"}),
        }

    # __init__ Django Crispy
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.form_show_labels = True
        self.helper.layout = layout_user_create

    # def clean_email(self):
    #     get_email = self.cleaned_data["username"]
    #     if UserCustom.objects.filter(email=get_email).exists():
    #         raise ValidationError(f"O email {get_email} já está em uso.")
    #     return get_email

    def save(self, commit=True):
        user = super().save(commit=False)
        # Assign password
        user.set_password(self.cleaned_data["password1"])
        # Save datas in Capitalize
        user.first_name = self.cleaned_data["first_name"].title()
        user.last_name = self.cleaned_data["last_name"].title()
        # Save data in lower text
        user.email = self.cleaned_data["username"]

        if commit:
            user.save()

            # Add permissions to here user
            if self.PERM_VIEWS:
                for perm in self.PERM_VIEWS:
                    with suppress(Exception):
                        permission = Permission.objects.get(name=perm)
                        user.user_permissions.add(permission)

            # Add user to group "read_only"
            # with suppress(Exception):
            # read_only = Group.objects.get(name='read_only')
            # user.groups.add(read_only)

        return user


class UserChangeFormCustom(UserChangeForm):
    class Meta:
        model = UserCustom
        fields = {"first_name", "last_name"}


# # Not customized
# class UserRegisterForm(UserCreationForm):
#     PERM_VIEWS = [
#         "Can view Client",
#     ]
#     email = forms.EmailField(max_length=100)

#     class Meta:
#         model = User
#         fields = ["username", "email", "first_name", "last_name"]

#     # Validar email se existe
#     def clean_email(self):
#         get_email = self.cleaned_data["email"]
#         if User.objects.filter(email=get_email).exists():
#             raise ValidationError(f"O email {get_email} já está em uso.")
#         return get_email

#     def save(self, commit=True):
#         user = super().save(commit=False)
#         # Save datas in Capitalize
#         user.first_name = self.cleaned_data["first_name"].title()
#         user.last_name = self.cleaned_data["last_name"].title()
#         # Save data in lower text
#         user.email = self.cleaned_data["email"].lower()
#         # Assign password
#         user.set_password(self.cleaned_data["password1"])

#         if commit:
#             user.save()

#             # Add permissions to here user
#             if self.PERM_VIEWS:
#                 for perm in self.PERM_VIEWS:
#                     with suppress(Exception):
#                         permission = Permission.objects.get(name=perm)
#                         user.user_permissions.add(permission)

#             # Add user to group "read_only"
#             # with suppress(Exception):
#             # read_only = Group.objects.get(name='read_only')
#             # user.groups.add(read_only)

#         return user

apps/users/views.py
from .forms import UserCreationFormCustom
from .forms import AuthenticationFormCustom
from django.views.generic.edit import CreateView
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy


class SignInView(LoginView):
    template_name = "users/signin.html"
    success_url = reverse_lazy("home_page")
    form_class = AuthenticationFormCustom
    redirect_authenticated_user = True
    success_message = "Logado"


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = "users/signup.html"
    success_url = reverse_lazy("sign-in")
    form_class = UserCreationFormCustom
    success_message = "Seu perfil foi criado com sucesso, basta fazer o login :)"

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("/")
        return super().dispatch(*args, **kwargs)


class ChangePasswordView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = "users/password_change.html"
    success_url = reverse_lazy("home_page")
    success_message = "Senha alterada com sucesso!"

management/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %} Tela de alteração de senha{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-4">
      <div class="card">
        <div class="card-body">

          <h2 class="text-center">Alteração de senha</h2>

          {% if form.errors %}
          <div class="alert alert-danger" role="alert">
            {{ form.old_password.errors }}
            {{ form.new_password1.errors }}
            {{ form.new_password2.errors }}
          </div>
          {% endif %}

          <form method="POST">
            {% csrf_token %}

            <div class="form-group pb-3">
              <label for="id_old_password">Senha antiga</label>
              <input type="password" name="old_password" id="id_old_password" class="form-control"
              id="old_password" placeholder="Senha antiga" required>
            </div>

            <div class="form-group pb-3">
              <label for="id_new_password">Nova senha</label>
              <input type="password" name="new_password1" id="id_new_password" class="form-control"
              id="new_password" placeholder="Nova senha" required>
              <small id="passwordHelp" class="form-text text-muted">
                <ul>
                  <li>Sua senha não pode ser muito parecida com o resto das suas informações pessoais.</li>
                  <li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                  <li>Sua senha não pode ser uma senha comumente utilizada.</li>
                  <li>Sua senha não pode ser inteiramente numérica.</li>
                </ul>
              </small>
            </div>

            <div class="form-group pb-3">
                <label for="id_new_password2">Confirmar senha</label>
                <input type="password" name="new_password2" id="id_new_password2" class="form-control"
                id="new_password1" placeholder="Confirmar senha" required>
              </div>

            <button type="submit" class="btn btn-primary" id="id_signup">Enviar</button>

          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

management/templates/users/signin.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block head %}{% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="sign-in">
  <div class="text-center sign-in__header">
    <img class="mb-4 rounded-circle" src="{% static 'images/logo.svg' %}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 fw-normal">Por favor, conecte-se</h1>
  </div>
  <div class="sign-in__body">
    <div class="card">
      <div class="card-body">
        {% crispy form %}
      </div>
    </div>
  </div>
</div>


<!-- <main class="text-center form-signin">
  <form method="POST" novalidate>
    {% csrf_token %}
    <img class="mb-4 rounded-circle" src="{% static 'images/logo.svg' %}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 fw-normal">Por favor, conecte-se</h1>

    <div class="form-floating">
      <input type="text" name="username" class="form-control" id="floatingInput" placeholder="E-Mail"
      autocapitalize="none" autocomplete="username" required>
      <label for="floatingInput">E-Mail</label>
    </div>
    <div class="form-floating">
      <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password"
      autocomplete="current-password" required>
      <label for="floatingPassword">Senha</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
  </form>
</main> -->

{% endblock %}

management/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class="sign-up">
  <div class="sign-up__header">
    <p class="h2 text-center"> Registrar-se</p>
  </div>
  <div class="sign-up__body">
    {% crispy form %}
		{{ form.errors }}
  </div>
</div>

<!--
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="card">
        <div class="card-body">

          <h2 class="text-center">Inscrever-se</h2>

          <form method="POST">
            {% csrf_token %}

            <div class="form-group pb-3">
              <label for="id_email">Username/E-mail</label>
              <input type="email" name="username" id="id_email" class="form-control" aria-describedby="emailHelp"
              placeholder="Enter email" required>
              <small id="emailHelp" class="form-text text-muted">Nunca compartilharemos seu e-mail com mais ninguém.</small>
              {% if form.username.errors %}
                <small class="form-text text-danger">{{ form.username.errors }}</small>
              {% endif %}
            </div>

            <div class="form-group pb-3">
              <label for="id_first_name">Primeiro nome</label>
              <input type="text" name="first_name" id="id_first_name" class="form-control"
              placeholder="First name" maxlength="30">
              {% if form.first_name.errors %}
                <small class="form-text text-danger">{{ form.first_name.errors }}</small>
              {% endif %}
            </div>

            <div class="form-group pb-3">
              <label for="id_last_name">Ultimo nome</label>
              <input type="text" name="last_name" id="id_last_name" class="form-control"
              placeholder="First name" maxlength="30">
              {% if form.last_name.errors %}
                <small class="form-text text-danger">{{ form.last_name.errors }}</small>
              {% endif %}
            </div>

            <div class="form-group">
              <label for="id_password1">Senha</label>
              <input type="password" name="password1" id="id_password1" class="form-control"
              id="exampleInputPassword1" placeholder="Password" required>
              {% if form.password1.errors %}
                <small class="form-text text-danger">{{ form.password1.errors }}</small>
              {% endif %}
              <small id="passwordHelp" class="form-text text-muted">
                <ul>
                  <li>Sua senha deve conter pelo menos 8 caracteres.</li>
                  <li>Sua senha não pode ser uma senha comumente usada.</li>
                  <li>Sua senha não pode ser totalmente numérica.</li>
                </ul>
              </small>
            </div>

            <div class="form-group pb-3">
              <label for="id_password2">Confirmar senha</label>
              <input type="password" name="password2" id="id_password2" class="form-control"
              id="exampleInputPasswordConfirm1" placeholder="Password" required>
              {% if form.password2.errors %}
                <small class="form-text text-danger">{{ form.password2.errors }}</small>
              {% endif %}
            </div>

            <button type="submit" class="btn btn-primary" id="id_signup" >Enviar</button>
          </form>

        </div>
      </div>
    </div>
  </div> -->

{% endblock %}